### ISSUE TITLE
create the heading and footer components

### ISSUE THREAD

**Issue by Amaan-Uddin** [GDSC-MJCET/AI-GENESIS#2]
## Components to be implemented
+ Add a ```<Prompt/>``` component which has basic information hinting the user generating their zombie-badge.
   (keep it short and simple)
   Add a button along with the prompt whose state change will trigger the ```<UserDetails/>``` component to render.

+ Add a simple ```<Footer/>``` , fixed to the bottom of the page.
   it must contain the current year, a copyright description and a simple _**made with <3 by web team**_ quote.

**Comment by Aymanquad** [comment]
what exactly do u want in the <prompt> and <UserDetails> ??

**Comment by Amaan-Uddin** [comment]
> what exactly do u want in the ```<Prompt/>``` and ```<UserDetails/>``` ??

1. Just add a simple **_"Enter your name and survival time to unlock a cool zombie badge🧟"_**
2. And I want ```<UserDetails/>``` component to be rendered when user presses the ```button``` in ```<Prompt/>``` component.

**Comment by Aymanquad** [comment]
Done .  
The complements are implemented on 'ayman' branch .
